apiVersion: v1
kind: Service
metadata:
  name: fastapi-template-service
  labels:
    service: fastapi-template
spec:
  selector:
    app: fastapi-template
  ports:
    - protocol: TCP
      port: 80
